version: '3'

services:
  app:
    build: .
    container_name: chatgpttoapi
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      ADMIN_PASSWORD: TotallySecurePassword
    volumes:
      - ./accounts.txt:/app/accounts.txt
      - ./cookies.json:/app/cookies.json
      - ./harPool:/app/harPool
